feat: CLI create and dream
aineko-dev/aineko pull request #104
Opened 2023-12-07 02:20 UTC by craycrayfish

## Summary

This PR enables the `--repo` option for the `aineko create` CLI. This allows users to initialize a repo by referencing a public GitHub repository.

To use, 

```
poetry run aineko create --repo Convex-Labs/dream-catcher#b1cda83d-a5e3-4341-9d4a-fdabc9691f94
```

This will load the pipeline config and node code from the specified branch in that repo.

## Motivation

This allows users to get started quicker with aineko pipelines, and paves the way for aineko-dream.

## Author Checklist

- [x] Changes are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Documentation is updated if necessary.
- [x] Status checks pass.
- [ ] If the version number is changed, it is updated in `pyproject.toml` , `aineko/__init__.py`, `aineko/templates/first_aineko_pipeline/{{cookiecutter.project_slug}}/pyproject.toml`.

## Reviewer Checklist

- [ ] Title is accurate and formatted appropriately.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Docs are updated if necessary.
- [ ] Code is pythonic and consistent with the rest of the codebase.
- [ ] The code is consistent with the [style guide](https://google.github.io/styleguide/pyguide.html).

2023-12-09 10:03 UTC, Barabazs requested changes
Can you document this and add more tests please?

2023-12-09 10:03 UTC, Barabazs commented on aineko/templates/first_aineko_pipeline/hooks/post_gen_project.py
> +if not truthy(with_deploy):
I would suggest using the native way instead of writing our own function for this:

```python
import distutils

bool(distutils.util.strtobool(with_deploy))
```

2023-12-09 10:03 UTC, Barabazs commented on tests/templates/first_aineko_pipeline/test_utils.py
Shouldn't this be mocked if it's a unit test.

2023-12-11 01:50 UTC, craycrayfish commented on tests/templates/first_aineko_pipeline/test_utils.py
I'm not familiar with best practices for this. Can you show me an example and let's agree on a standard to use within our repos

2023-12-11 01:50 UTC, craycrayfish commented
> Can you document this and add more tests please?

Docs are described in the docstrings and will show up in the CLI section of the docs. Do you think we need more?

2023-12-11 09:13 UTC, Barabazs commented
> > Can you document this and add more tests please?
> 
> Docs are described in the docstrings and will show up in the CLI section of the docs. Do you think we need more?

Ok, that might be good enough. I didn't think of that.

2023-12-11 09:20 UTC, Barabazs commented on tests/templates/first_aineko_pipeline/test_utils.py
I think a great comprehensive resources on this is [The Practical Test Pyramid](https://martinfowler.com/articles/practical-test-pyramid.html). But rereading it made me realise that real life components can be invoked if needed. [UnitTests](https://martinfowler.com/articles/practical-test-pyramid.html#UnitTests)

2023-12-11 15:58 UTC, craycrayfish commented on aineko/templates/first_aineko_pipeline/hooks/post_gen_project.py
> +if not truthy(with_deploy):
Unfortunately that seems to be deprecated, the advice is to implement it yourself: https://peps.python.org/pep-0632/#migration-advice

2023-12-12 16:26 UTC, Barabazs approved these changes

2023-12-13 21:00 UTC, merged